*** Settings ***
Resource        ${CURDIR}${/}..${/}keywords${/}eordering${/}api${/}es_14_api.resource
Resource        ${CURDIR}${/}..${/}keywords${/}eordering${/}api${/}es_15_api.resource
Resource        ${CURDIR}${/}..${/}keywords${/}eordering${/}api${/}yt-65218_api.resource
Resource        ${CURDIR}${/}..${/}keywords${/}eordering${/}api${/}lp_01_api.resource
Resource        ${CURDIR}${/}..${/}keywords${/}eordering${/}api${/}lp_03_api.resource